MiniNetflix/Controllers/GenreController.cs
using Application.IServices;
using Application.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace MiniNetflix.Controllers
{
    public class GenreController : Controller
    {
     private readonly IGenresService _genresService;

     public GenreController(IGenresService genresService)
     {
         _genresService = genresService;
     }

     public IActionResult Index()
     {
         var genres = _genresService.GetAllGenres();
         return View(genres);
     }


     public IActionResult Create()
     {
         return View();
     }

     [HttpPost]
     [ValidateAntiForgeryToken]
     public IActionResult Create(GenreViewModel genre)
     {
         if (ModelState.IsValid)
         {
             _genresService.Add(genre);
             return RedirectToAction(nameof(Index));
         }
         return View(genre);
     }

     public IActionResult Edit(int id)
     {
         var genre = _genresService.GetById(id);
         if (genre == null)
         {
             return NotFound();
         }
         return View(genre);
     }

     [HttpPost]
     [ValidateAntiForgeryToken]
     public IActionResult Edit(int id, GenreViewModel genre)
     {
         if (id != genre.Id)
         {
             return NotFound();
         }

         if (ModelState.IsValid)
         {
             _genresService.Update(genre);
             return RedirectToAction(nameof(Index));
         }
         return View(genre);
     }

     [HttpPost]
     [ValidateAntiForgeryToken]
     public IActionResult Delete(int id)
     {
         var genre = _genresService.GetById(id);
         if (genre == null)
         {
             return NotFound();
         }

        
         if (_genresService.HasSeries(id))
         {

                TempData["ErrorMessage"] = "No puedes eliminar un genero que contiene series.";
                return RedirectToAction(nameof(Index));
         }

       
         _genresService.Delete(id);

         return RedirectToAction(nameof(Index));
     }


    }
}

MiniNetflix/Controllers/ProducerController.cs
using Application.IServices;
using Application.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace MiniNetflix.Controllers
{
    public class ProducerController : Controller
    {
        private readonly IProducerService _producerService;

        public ProducerController(IProducerService producerService)
        {
            _producerService = producerService;
        }

        public IActionResult Index()
        {
            var producers = _producerService.GetAllProducer();
            return View(producers);
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ProducerViewModel producerViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(producerViewModel);
            }

            _producerService.Add(producerViewModel);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int id)
        {
            var producer = _producerService.GetById(id);
            if (producer == null)
            {
                return NotFound();
            }
            return View(producer);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ProducerViewModel producerViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(producerViewModel);
            }

            _producerService.Update(producerViewModel);
            return RedirectToAction(nameof(Index));
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            if (_producerService.HasSeries(id))
            {
                
                TempData["ErrorMessage"] = "No puedes eliminar un productor que contiene series.";
                return RedirectToAction(nameof(Index));
            }
            _producerService.Delete(id);
            return RedirectToAction(nameof(Index));
        }



    }
}

MiniNetflix/Controllers/SeriesController.cs
using Application.IServices;

using Application.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MiniNetflix.Controllers
{
    public class SeriesController : Controller
    {
        private readonly ISeriesService _seriesService;
        private readonly IProducerService _producerService;
        private readonly IGenresService _genreService; 

        public SeriesController(ISeriesService seriesService, IProducerService producerService, IGenresService genreService)
        {
            _seriesService = seriesService;
            _producerService = producerService;
            _genreService = genreService;
        }

        public IActionResult Index()
        {
            var series = _seriesService.GetAllSeries();
            return View(series);
        }


        public IActionResult Create()
        {
            var model = new SeriesViewModel
            {
                Producers = GetProducers(),
                PrimaryGenres = GetPrimaryGenres(),
                SecondaryGenres = GetSecondaryGenres()
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(SeriesViewModel seriesViewModel)
        {
            if (!ModelState.IsValid)
            {
                seriesViewModel.Producers = GetProducers();
                seriesViewModel.PrimaryGenres = GetPrimaryGenres();
                seriesViewModel.SecondaryGenres = GetSecondaryGenres();
                return View(seriesViewModel);
            }

            _seriesService.Add(seriesViewModel);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int id)
        {
            var series = _seriesService.GetById(id);
            if (series == null)
            {
                return NotFound();
            }

            var model = new SeriesViewModel
            {
                Id = series.Id,
                Name = series.Name,
                VideoLink = series.VideoLink,
                ImgLink = series.ImgLink,
                ProducerId = series.ProducerId,
                PrimaryGenreId = series.PrimaryGenreId,
                SecondaryGenreId = series.SecondaryGenreId,
                Producers = GetProducers(),
                PrimaryGenres = GetPrimaryGenres(),
                SecondaryGenres = GetSecondaryGenres()
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(SeriesViewModel seriesViewModel)
        {
            if (!ModelState.IsValid)
            {
               
                seriesViewModel.Producers = GetProducers();
                seriesViewModel.PrimaryGenres = GetPrimaryGenres();
                seriesViewModel.SecondaryGenres = GetSecondaryGenres();
                return View(seriesViewModel);
            }

            _seriesService.Update(seriesViewModel);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _seriesService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        private List<SelectListItem> GetProducers()
        {
            var producers = _producerService.GetAllProducer(); 
            return producers.Select(p => new SelectListItem
            {
                Value = p.Id.ToString(),
                Text = p.Name
            }).ToList();
        }

        private List<SelectListItem> GetPrimaryGenres()
        {
            var genres = _genreService.GetAllGenres();
            return genres.Select(g => new SelectListItem
            {
                Value = g.Id.ToString(),
                Text = g.Name
            }).ToList();
        }

        private List<SelectListItem> GetSecondaryGenres()
        {
            var genres = _genreService.GetAllGenres(); 
            return genres.Select(g => new SelectListItem
            {
                Value = g.Id.ToString(),
                Text = g.Name
            }).ToList();
        }
    }
}

MiniNetflix/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MiniNetflix</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MiniNetflix.styles.css" asp-append-version="true" />

 
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">

    <style>
        body {
            background-color: #141414; 
            color: white; 
            font-family: 'Poppins', sans-serif; 
        }

        .navbar {
            background-color: #e50914; 
            border-bottom: 1px solid #333; 
        }

        .navbar-brand, .nav-link {
            color: white !important;
        }

            .nav-link:hover {
                color: #b3b3b3 !important; 
            }

        footer {
            background-color: #333; 
            color: #b3b3b3; 
        }

            footer a {
                color: #e50914; 
            }

                footer a:hover {
                    color: white; 
                }

     
        header {
            font-family: 'Poppins', sans-serif; 
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MiniNetflix</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Genre" asp-action="Index">Mant. Genero</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Producer" asp-action="Index">Mant. Productores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Series" asp-action="Index">Mant. Series</a>
                        </li>
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MiniNetflix
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>